@startuml

!include ../include/default.iuml

left to right direction
hide empty members


rectangle ChronicleDomains as "Chronicle" {
rectangle "Chronicle domain one" as DomainOnePackage {
  component "Chronicle" as ChronicleDomainOne
  database "Index database" as IndexOne
  component "Customer service" as CustomerService
}
}

rectangle "Sawtooth" as SawtoothPackage  {
    component "Sawtooth validator"  as Sawtooth
    rectangle ChronicleTpEmbed as "Chronicle" {
        component "Chronicle Transaction Processor" as ChronicleTP
    }
}

CustomerService <-> ChronicleDomainOne: invokes
ChronicleDomainOne <-> IndexOne : Indexes PROV
ChronicleDomainOne --> Sawtooth: Submits transaction
ChronicleTP <-> Sawtooth: Confirms transaction

@enduml
