!include ../include/default.iuml

@startuml

#darkcyan:(U)
:received token;
if (--userinfo-address?
or auth.userinfo.uri?) then (absent)
  :no claims;
else (present)
  if (userinfo\nresult cached?) then (no)
    :query userinfo endpoint;
  else (yes)
  endif
  switch (userinfo\nresponse\nto token)
  case (JWT)
    #darkcyan:(J)
  case (JSON object)
  case (other)
    #darkred:reject
    request;
    detach
  endswitch
  :valid claims;
endif
stop

@enduml
