@startuml

!include ../include/default.iuml

!include ../include/agent.iuml
!include ../include/activity.iuml
!include ../include/entity.iuml

Guidance <|-- entity
PublishedGuidance <|-- entity
Person <|-- agent
Publication <|-- activity


Person -> Publication: wasAssociatedWith
note on link: Role: Stakeholder
Person -> Person: actedOnBehalfOf
note on link: Role: Stakeholder
Person -> Publication: wasAssociatedWith
note on link: Role: Editor
PublishedGuidance -> Revision: hadPrimarySource
Publication -> Guidance : used
PublishedGuidance -> Publication: wasGeneratedBy
PublishedGuidance -> Document: hadEvidence

@enduml
