@startuml

!include ../include/default.iuml

!include ../include/agent.iuml
!include ../include/activity.iuml
!include ../include/entity.iuml

Question <|-- Entity
Person <|-- Agent
Organization <|-- Agent
QuestionAsked <|-- Activity

Person -> QuestionAsked : wasAssociatedWith
note on link: (role=Stakeholder)
Organization -> QuestionAsked : wasAssociatedWith
note on link: (role=Stakeholder)
Person -> QuestionAsked : wasAssociatedWith
note on link: (role=Author)
Question -> QuestionAsked : wasGeneratedBy

@enduml
