@startuml

!include ../include/default.iuml

!include ../include/agent.iuml
!include ../include/activity.iuml
!include ../include/entity.iuml

Question <|-- entity
Evidence <|-- entity
Person <|-- agent
Researched <|-- activity

Person -> Researched : wasAssociatedWith
note on link: Role: Researcher
Question -> Researched : used
Evidence -> Researched : wasGeneratedBy

@enduml
