@startuml

!include ../include/default.iuml

!include ../include/agent.iuml
!include ../include/activity.iuml
!include ../include/entity.iuml

Question <|-- Entity
Evidence <|-- Entity
Person <|-- Agent
Researched <|-- Activity

Person -> Researched : wasAssociatedWith
note on link: (role=Researcher)
Question -> Researched : used
Evidence -> Researched : wasGeneratedBy

@enduml
