@startuml

!include ../include/default.iuml

actor "Editor"
actor "Author"

Guidance -> Question : Has context
Author -> Guidance : Creates version
Author -> EvidenceReference : Reviews
Author -> Guidance : Authors
Guidance -> EvidenceReference : References
Editor -> Author: Helps refine

@enduml
