@startuml

!include ../include/default.iuml

!include ../include/activity.iuml
!include ../include/entity.iuml

Question <|-- entity
Guidance <|-- entity
Evidence <|-- entity
Revised <|-- activity

Question -> Revised : used
Evidence -> Revised : used
Guidance -> Revised : wasGeneratedBy
Guidance -> Guidance : wasRevisionOf
Question -> Guidance : hadPrimarySource

@enduml
