@startuml

!include ../include/default.iuml

!include ../include/activity.iuml
!include ../include/entity.iuml

Question <|-- Entity
Guidance <|-- Entity
Evidence <|-- Entity
Revised <|-- Activity

Question -> Revised : used
Evidence -> Revised : used
Guidance -> Revised : wasGeneratedBy
Guidance -> Guidance : wasRevisionOf
Question -> Guidance : hadPrimarySource

@enduml
