@startuml
skinparam componentStyle rectangle


component "Chronicle" {
    database PostgreSQL

    file keystore

    () CLI

    [API]

    [graphql playground]

    () GraphQL
}


component "Sawtooth" {
    [sawtooth API]

    [sawtooth transaction processor]
}

[Apollo Server]



[Apollo Server] <..> GraphQL: federates
[API] ..> [graphql playground]: serves
[graphql playground] <..> GraphQL
CLI <..> API: spawns or uses remote
CLI <..> GraphQL: uses
[API] <..> GraphQL
[API] <..> PostgreSQL
[API] <..> keystore
[API] <..> [sawtooth API]

[sawtooth API] <..> [sawtooth transaction processor]

@enduml
