[package]
edition = "2021"
name = "pallet-opa"
version = "0.7.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

common = { path = "../common", default-features = false, features = [
    "parity-encoding",
] }

# Start Generation Here
frame-benchmarking = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.9.0', default-features = false, optional = true }
frame-support = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.9.0', default-features = false }
frame-system = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.9.0', default-features = false }
sp-core = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.9.0', default-features = false }
sp-core-hashing = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.9.0', default-features = false }
sp-std = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.9.0', default-features = false }
k256 = { version = "0.11", default-features = false, features = [
    "arithmetic",
    "ecdsa",
    "pkcs8",
    "pem",
] }
macro-attr-2018 = { workspace = true }
newtype-derive-2018 = { workspace = true }
parity-scale-codec = { version = "^3.4.0", default-features = false, features = [
    "derive",
] }
scale-info = { version = "^2.10.0", default-features = false, features = [
    "derive",
] }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
tracing = { version = "0.1", default-features = false, features = [
    "attributes",
] }
uuid = { version = "1.5", default-features = false }


[dev-dependencies]
chronicle-telemetry = { path = "../chronicle-telemetry" }
sp-core = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.9.0' }
sp-io = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.9.0' }
sp-runtime = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.9.0' }
uuid = { version = "1.5.0", default-features = false }


[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
    "common/std",
    "k256/std",
    "parity-scale-codec/std",
    "uuid/std",
    "sp-std/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "tracing/std",
]
try-runtime = ["frame-support/try-runtime"]
