[package]
authors     = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
description = "A fresh FRAME-based Substrate node, ready for hacking."
edition     = "2021"
homepage    = "https://substrate.io/"
license     = "MIT-0"
name        = "runtime-chronicle"
publish     = false
version     = "4.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-executive = { version = "25.0.0", default-features = false }
frame-support = { version = "25.0.0", default-features = false }
frame-system = { version = "25.0.0", default-features = false }
frame-try-runtime = { version = "0.31.0", default-features = false, optional = true }
pallet-aura = { version = "24.0.0", default-features = false }
pallet-grandpa = { version = "25.0.0", default-features = false }
pallet-sudo = { version = "25.0.0", default-features = false }
pallet-timestamp = { version = "24.0.0", default-features = false }
parity-scale-codec = { version = "^3.4.0", default-features = false, features = [
  "derive",
] }
scale-info = { version = "^2.10.0", default-features = false, features = [
  "derive",
] }
sp-api = { version = "23.0.0", default-features = false }
sp-block-builder = { version = "23.0.0", default-features = false }
sp-consensus-aura = { version = "0.29.0", default-features = false }
sp-consensus-grandpa = { version = "10.0.0", default-features = false }
sp-core = { version = "25.0.0", default-features = false }
sp-inherents = { version = "23.0.0", default-features = false }
sp-offchain = { version = "23.0.0", default-features = false }
sp-runtime = { version = "28.0.0", default-features = false }
sp-session = { version = "24.0.0", default-features = false }
sp-std = { version = "12.0.0", default-features = false }
sp-transaction-pool = { version = "23.0.0", default-features = false }
sp-version = { version = "26.0.0", default-features = false }

# Used for the node template's RPCs
frame-system-rpc-runtime-api = { version = "23.0.0", default-features = false }

# Used for runtime benchmarking
frame-benchmarking        = { version = "25.0.0", default-features = false, optional = true }
frame-system-benchmarking = { version = "25.0.0", default-features = false, optional = true }

# Local Dependencies
pallet-chronicle      = { default-features = false, path = "../../crates/pallet-chronicle" }
pallet-opa            = { default-features = false, path = "../../crates/pallet-opa" }
runtime-api-chronicle = { default-features = false, path = "../../crates/runtime-api-chronicle" }

[build-dependencies]
substrate-wasm-builder = { version = "14.0.0", optional = true }

[features]
default = ["std"]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system-benchmarking/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-grandpa/runtime-benchmarks",
  "pallet-sudo/runtime-benchmarks",
  "pallet-chronicle/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
std = [
  "pallet-chronicle/std",
  "runtime-api-chronicle/std",
  "frame-try-runtime?/std",
  "frame-system-benchmarking?/std",
  "frame-benchmarking?/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "frame-executive/std",
  "frame-support/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "frame-try-runtime/std",
  "pallet-aura/std",
  "pallet-grandpa/std",
  "pallet-sudo/std",
  "pallet-chronicle/std",
  "pallet-timestamp/std",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-consensus-grandpa/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-std/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  "substrate-wasm-builder",
]
try-runtime = [
  "frame-try-runtime/try-runtime",
  "frame-executive/try-runtime",
  "frame-system/try-runtime",
  "frame-support/try-runtime",
  "pallet-aura/try-runtime",
  "pallet-grandpa/try-runtime",
  "pallet-sudo/try-runtime",
  "pallet-chronicle/try-runtime",
  "pallet-timestamp/try-runtime",
]
