[package]
authors     = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
build       = "build.rs"
description = "A fresh FRAME-based Substrate node, ready for hacking."
edition     = "2021"
homepage    = "https://substrate.io/"
license     = "MIT-0"
name        = "node-chronicle"
publish     = false
repository  = "https://github.com/substrate-developer-hub/substrate-node-template/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-chronicle"
path = "src/main.rs"

[lib]
name = "node_chronicle"
path = "src/lib.rs"

[dependencies]
clap                    = { version = "4.4.2", features = ["derive"] }
frame-system            = { version = "25.0.0" }
futures                 = { version = "0.3.21", features = ["thread-pool"] }
sc-cli                  = { version = "0.33.0" }
sc-client-api           = { version = "25.0.0" }
sc-consensus            = { version = "0.30.0" }
sc-consensus-aura       = { version = "0.31.0" }
sc-consensus-grandpa    = { version = "0.16.0" }
sc-executor             = { version = "0.29.0" }
sc-network              = { version = "0.31.0" }
sc-offchain             = { version = "26.0.0" }
sc-service              = { version = "0.32.0" }
sc-statement-store      = { version = "7.0.0" }
sc-telemetry            = { version = "12.0.0" }
sc-transaction-pool     = { version = "25.0.0" }
sc-transaction-pool-api = { version = "25.0.0" }
sp-consensus-aura       = { version = "0.29.0" }
sp-consensus-grandpa    = { version = "10.0.0" }
sp-core                 = { version = "25.0.0" }
sp-inherents            = { version = "23.0.0" }
sp-io                   = { version = "27.0.0" }
sp-keyring              = { version = "28.0.0" }
sp-runtime              = { version = "28.0.0" }
sp-timestamp            = { version = "23.0.0" }
tracing                 = { workspace = true }

# These dependencies are used for the node template's RPCs
jsonrpsee                  = { version = "0.16", features = ["server"] }
sc-basic-authorship        = { version = "0.31.0" }
sc-rpc-api                 = { version = "0.30.0" }
sp-api                     = { version = "23.0.0" }
sp-block-builder           = { version = "23.0.0" }
sp-blockchain              = { version = "25.0.0" }
substrate-frame-rpc-system = { version = "25.0.0" }

# These dependencies are used for runtime benchmarking
frame-benchmarking     = { version = "25.0.0" }
frame-benchmarking-cli = { version = "29.0.0" }

# Local Dependencies
runtime-chronicle = { path = "../runtime-chronicle" }

# CLI-specific dependencies
try-runtime-cli = { version = "0.35.0", optional = true }

[build-dependencies]
substrate-build-script-utils = { version = "9.0.0" }

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
  "runtime-chronicle/runtime-benchmarks",
  "frame-benchmarking/runtime-benchmarks",
  "frame-benchmarking-cli/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["runtime-chronicle/try-runtime", "try-runtime-cli/try-runtime"]
