---
{{$stlServiceName := include "lib.call-nested" (list . "node" "common.names.fullname")}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-chronicle-config
data:
  config.toml: |
    [namespace_bindings]
    default = "fd717fd6-70f1-44c1-81de-287d5e101089"
