[package]
name = "runtime-api-chronicle"
version = "1.0.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { version = "23.0.0", default-features = false }
sp-core = { version = "25.0.0", default-features = false }

#Local dependencies
common = { path = "../common", default-features = false, features = ["parity-encoding"] }

[features]
default = ["std"]
std = [
    "sp-api/std",
    "common/std"
]
