# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/persistence/schema.rs"
import_types = ["diesel::sql_types::*", "common::prov::*"]
