[package]
name = "pallet-chronicle"
edition = "2021"
version = "0.7.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

common = {path = "../common", default-features=false, features=["parity"]}
parity-scale-codec = { version="3.6.5", default-features = false, features = ["derive"] }
uuid = {version="1.5.0", default-features=false}
sp-std = { version="11.0.0", default-features = false}
scale-info = { version="2.10.0", default-features = false, features = ["derive"] }
frame-support = { version="24.0.0", default-features=false }
frame-system = { version= "24.0.0",default-features=false }
frame-benchmarking = { version = "24.0.0", default-features = false, optional=true}
tracing = {version="0.1.40", default-features=false, features=["attributes"]}
newtype-derive-2018 = {workspace=true}
macro-attr-2018 = {workspace=true}

[dev-dependencies]
sp-runtime = { version="27.0.0"}
sp-io = {version="26.0.0" }
sp-core = {version="24.0.0"}
chronicle-telemetry = {path="../chronicle-telemetry"}

[features]
default = ["std"]
std = [
	"common/std",
	"parity-scale-codec/std",
	"uuid/std",
	"sp-std/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"tracing/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
