#!/usr/bin/env bash

HOST=chronicle-sawtooth-api
PORT=9982
TIMEOUT=300
echo "Wait for stack"
if ! wait-for-it -h $HOST -p $PORT -t $TIMEOUT; then
  echo "Timed out waiting for $HOST"
  exit 1
fi
sleep 20

echo "Subscribe to commits"
gq http://$HOST:$PORT/ws -q " \
subscription { \
  commitNotifications { \
    stage \
    delta \
    txId \
    error \
  } \
}" >subscription.out &

sleep 5

echo "Issue query"
gq http://$HOST:$PORT -q " \
mutation{ \
        defineAgent( \
    externalId: \"test\",  \
    attributes: {}) { \
    txId \
  } \
}"

echo "Collecting commits"
sleep 30

cat subscription.out

grep COMMIT subscription.out
