@startuml

actor "Stakeholder"
actor "Clinician"

Guidance -> Question : Has context
Author -> Guidance : Creates version
Author -> Evidence : Reviews
Author -> Guidance : Authors
Guidance -> Evidence : References
Editor -> Author: Helps refine

@enduml
